server:
  port: 8080

spring:
  application:
    name: service-consumer

eureka:
  client:
    service-url:
      #设置与Eureka Server交互的地址，查询服务和注册服务都需要依赖这个地址。默认是http://localhost:8761/eureka ；多个地址可使用 , 分隔。
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/,http://localhost:8763/eureka/


feign:
  hystrix:
    enabled: true
