server:
  port: 8763

eureka:
  instance:
    hostname: peer3
  client:
    service-url:
      #设置与Eureka Server交互的地址，查询服务和注册服务都需要依赖这个地址。默认是http://localhost:8761/eureka ；多个地址可使用 , 分隔。
      defaultZone: http://peer1:8761/eureka/,http://peer2:8762/eureka/

spring:
  application:
    name: eureka-server-peer3